framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false
    handle_all_throwables: true
    assets:
        packages:
            api_platform:
                base_path: '/bundles/apiplatform'
    error_controller: error_controller